# Generated by Django 4.2.20 on 2025-03-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRequest',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Reason', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Attendance_Request',
            },
        ),
    ]
