# Generated by Django 5.1.7 on 2025-03-20 21:35

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DetailsAdminPanel', '0005_userattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttendance',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('DetailsAdminPanel.userattendance',),
        ),
    ]
