# Generated by Django 4.2.20 on 2025-04-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsUserPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastAttendanceRequest',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=50)),
                ('Reason', models.TextField(max_length=250)),
                ('Status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Past_Attendance_Request',
            },
        ),
    ]
