# Generated by Django 4.2.18 on 2025-03-21 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsUserPanel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAttendance',
        ),
    ]
