# Generated by Django 5.1.7 on 2025-03-25 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('userEmail', models.CharField(max_length=100)),
                ('userDepartment', models.CharField(max_length=50)),
                ('userDesignation', models.CharField(max_length=50)),
                ('userPhoto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_password', models.CharField(default='default_password', max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Registration.user')),
            ],
        ),
    ]
