# Generated by Django 5.1.7 on 2025-03-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('userEmail', models.CharField(max_length=100)),
                ('userDepartment', models.CharField(max_length=50)),
                ('userDesignation', models.CharField(max_length=50)),
                ('userPhoto', models.CharField(max_length=50)),
            ],
        ),
    ]
