# Generated by Django 4.2.20 on 2025-04-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=100)),
                ('departmentHead', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
    ]
