# Generated by Django 5.1.5 on 2025-04-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Registration", "0002_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="logindetails",
            name="role",
            field=models.CharField(default="user", max_length=20),
            preserve_default=False,
        ),
    ]
