# Generated by Django 5.1.7 on 2025-03-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_alter_user_userphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPhoto',
            field=models.ImageField(upload_to=''),
        ),
    ]
