# Generated by Django 5.1.7 on 2025-03-25 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='Registration.user')),
            ],
            options={
                'db_table': 'user_attendance',
            },
        ),
    ]
