# Generated by Django 4.2.18 on 2025-03-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='user_images/')),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
