# Generated by Django 4.2.18 on 2025-03-24 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
        ('DetailsAdminPanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userattendance',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='Registration.user'),
        ),
    ]
