# Generated by Django 4.2.18 on 2025-03-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsAdminPanel', '0002_alter_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='id',
        ),
    ]
