# Generated by Django 4.2.18 on 2025-03-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsAdminPanel', '0003_rename_userid_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
