# Generated by Django 4.2.18 on 2025-03-21 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsAdminPanel', '0005_userattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattendance',
            name='id',
        ),
        migrations.AlterField(
            model_name='userattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DetailsAdminPanel.user'),
        ),
    ]
