# Generated by Django 4.2.20 on 2025-03-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('hashed_password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Registration_logindetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_id', models.CharField(max_length=50, unique=True)),
                ('hashed_password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'admin_credentials',
            },
        ),
    ]
