# Generated by Django 5.1.7 on 2025-03-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationLoginDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hashed_password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Registration_logindetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationUser',
            fields=[
                ('userId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('userEmail', models.EmailField(max_length=100, unique=True)),
                ('userDepartment', models.CharField(max_length=50)),
                ('userDesignation', models.CharField(max_length=50)),
                ('userPhoto', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Registration_user',
                'managed': False,
            },
        ),
    ]
