# Generated by Django 5.1.5 on 2025-04-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Login", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(max_length=50, unique=True)),
                ("hashed_password", models.CharField(max_length=128)),
                ("role", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "Registration_logindetails",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="AdminUser",
        ),
        migrations.DeleteModel(
            name="NormalUser",
        ),
    ]
