import { Injectable } from "@angular/core";
import { Student } from "../models/student.model";

@Injectable({
  providedIn: 'root'
})

export class StudentService {
      student : Student [] = [
        { id: 1, fullName: 'John Doe', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:30 AM', isEditing: false },
            { id: 2, fullName: 'Jane Smith', designation: 'Student', department: 'Mathematics', status: 'Absent', time: 'N/A', isEditing: false },
            { id: 3, fullName: 'Emily Johnson', designation: 'Student', department: 'Physics', status: 'Late', time: '09:15 AM', isEditing: false },
            { id: 4, fullName: 'John', designation: 'Teacher', department: 'Computer Science', status: 'Present', time: '08:31 AM', isEditing: false },
            { id: 5, fullName: 'Alice Brown', designation: 'Student', department: 'Biology', status: 'Present', time: '08:45 AM', isEditing: false },
            { id: 6, fullName: 'Michael Green', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:10 AM', isEditing: false },
            { id: 7, fullName: 'Chris White', designation: 'Student', department: 'Physics', status: 'Present', time: '08:50 AM', isEditing: false },
            { id: 8, fullName: 'Jessica Lee', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:20 AM', isEditing: false },
            { id: 9, fullName: 'David Kim', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:40 AM', isEditing: false },
            { id: 10, fullName: 'Sophia Clark', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', isEditing: false },
            { id: 11, fullName: 'Daniel Martinez', designation: 'Student', department: 'Physics', status: 'Late', time: '09:10 AM', isEditing: false },
            { id: 12, fullName: 'Olivia Hernandez', designation: 'Student', department: 'Biology', status: 'Present', time: '08:35 AM', isEditing: false },
            { id: 13, fullName: 'William Scott', designation: 'Teacher', department: 'Mathematics', status: 'Present', time: '08:32 AM', isEditing: false },
            { id: 14, fullName: 'Isabella Adams', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:05 AM', isEditing: false },
            { id: 15, fullName: 'James Carter', designation: 'Student', department: 'Chemistry', status: 'Present', time: '08:55 AM', isEditing: false },
            { id: 16, fullName: 'Charlotte Lewis', designation: 'Student', department: 'Biology', status: 'Late', time: '09:05 AM', isEditing: false },
            { id: 17, fullName: 'Benjamin Walker', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:48 AM', isEditing: false },
            { id: 18, fullName: 'Mia Hall', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', isEditing: false },
            { id: 19, fullName: 'Ethan Allen', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:42 AM', isEditing: false },
            { id: 20, fullName: 'Harper Young', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:18 AM', isEditing: false },
            { id: 21, fullName: 'Alexander King', designation: 'Student', department: 'Physics', status: 'Present', time: '08:47 AM', isEditing: false },
            { id: 22, fullName: 'Amelia Nelson', designation: 'Student', department: 'Chemistry', status: 'Absent', time: 'N/A', isEditing: false },
            { id: 23, fullName: 'Lucas Robinson', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:51 AM', isEditing: false },
            { id: 24, fullName: 'Ella Baker', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:12 AM', isEditing: false }
          
      ];

      getStudents() {
        return this.student;
      }

      loggedinStudents= [
        
        { id: 1, fullName: 'John Doe', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:55 AM', date: '2024-02-01' },
{ id: 1, fullName: 'John Doe', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:30 AM', date: '2024-02-02' },
{ id: 1, fullName: 'John Doe', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:25 AM', date: '2024-02-03' },
{ id: 1, fullName: 'John Doe', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-04' },
{ id: 1, fullName: 'John Doe', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:25 AM', date: '2024-02-05' },
{ id: 1, fullName: 'John Doe', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:25 AM', date: '2024-02-06' },
{ id: 1, fullName: 'John Doe', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:05 AM', date: '2024-02-07' },
{ id: 1, fullName: 'John Doe', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:40 AM', date: '2024-02-08' },
{ id: 1, fullName: 'John Doe', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:20 AM', date: '2024-02-09' },
{ id: 1, fullName: 'John Doe', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:40 AM', date: '2024-02-10' },
{ id: 1, fullName: 'John Doe', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-11' },
{ id: 1, fullName: 'John Doe', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:15 AM', date: '2024-02-12' },
{ id: 1, fullName: 'John Doe', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-13' },
{ id: 1, fullName: 'John Doe', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:55 AM', date: '2024-02-14' },
{ id: 1, fullName: 'John Doe', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:35 AM', date: '2024-02-15' },
{ id: 1, fullName: 'John Doe', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:50 AM', date: '2024-02-16' },
{ id: 1, fullName: 'John Doe', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:20 AM', date: '2024-02-17' },
{ id: 1, fullName: 'John Doe', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-18' },
{ id: 1, fullName: 'John Doe', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-19' },
{ id: 1, fullName: 'John Doe', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:05 AM', date: '2024-02-20' },
{ id: 2, fullName: 'Jane Smith', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:20 AM', date: '2024-02-01' },
{ id: 2, fullName: 'Jane Smith', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:10 AM', date: '2024-02-02' },
{ id: 2, fullName: 'Jane Smith', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:05 AM', date: '2024-02-03' },
{ id: 2, fullName: 'Jane Smith', designation: 'Student', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-04' },
{ id: 2, fullName: 'Jane Smith', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:05 AM', date: '2024-02-05' },
{ id: 2, fullName: 'Jane Smith', designation: 'Student', department: 'Mathematics', status: 'Present', time: '08:40 AM', date: '2024-02-06' },
{ id: 2, fullName: 'Jane Smith', designation: 'Student', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-07' },
{ id: 2, fullName: 'Jane Smith', designation: 'Student', department: 'Mathematics', status: 'Present', time: '08:35 AM', date: '2024-02-08' },
{ id: 2, fullName: 'Jane Smith', designation: 'Student', department: 'Mathematics', status: 'Present', time: '08:35 AM', date: '2024-02-09' },
{ id: 2, fullName: 'Jane Smith', designation: 'Student', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-10' },
{ id: 2, fullName: 'Jane Smith', designation: 'Student', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-11' },
{ id: 2, fullName: 'Jane Smith', designation: 'Student', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-12' },
{ id: 2, fullName: 'Jane Smith', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:15 AM', date: '2024-02-13' },
{ id: 2, fullName: 'Jane Smith', designation: 'Student', department: 'Mathematics', status: 'Present', time: '08:55 AM', date: '2024-02-14' },
{ id: 2, fullName: 'Jane Smith', designation: 'Student', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-15' },
{ id: 2, fullName: 'Jane Smith', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:25 AM', date: '2024-02-16' },
{ id: 2, fullName: 'Jane Smith', designation: 'Student', department: 'Mathematics', status: 'Present', time: '08:40 AM', date: '2024-02-17' },
{ id: 2, fullName: 'Jane Smith', designation: 'Student', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-18' },
{ id: 2, fullName: 'Jane Smith', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:15 AM', date: '2024-02-19' },
{ id: 2, fullName: 'Jane Smith', designation: 'Student', department: 'Mathematics', status: 'Present', time: '08:30 AM', date: '2024-02-20' },
{ id: 3, fullName: 'Emily Johnson', designation: 'Student', department: 'Physics', status: 'Late', time: '09:10 AM', date: '2024-02-01' },
{ id: 3, fullName: 'Emily Johnson', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-02' },
{ id: 3, fullName: 'Emily Johnson', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-03' },
{ id: 3, fullName: 'Emily Johnson', designation: 'Student', department: 'Physics', status: 'Late', time: '09:15 AM', date: '2024-02-04' },
{ id: 3, fullName: 'Emily Johnson', designation: 'Student', department: 'Physics', status: 'Present', time: '08:30 AM', date: '2024-02-05' },
{ id: 3, fullName: 'Emily Johnson', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-06' },
{ id: 3, fullName: 'Emily Johnson', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-07' },
{ id: 3, fullName: 'Emily Johnson', designation: 'Student', department: 'Physics', status: 'Present', time: '08:35 AM', date: '2024-02-08' },
{ id: 3, fullName: 'Emily Johnson', designation: 'Student', department: 'Physics', status: 'Late', time: '09:10 AM', date: '2024-02-09' },
{ id: 3, fullName: 'Emily Johnson', designation: 'Student', department: 'Physics', status: 'Late', time: '09:20 AM', date: '2024-02-10' },
{ id: 3, fullName: 'Emily Johnson', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-11' },
{ id: 3, fullName: 'Emily Johnson', designation: 'Student', department: 'Physics', status: 'Late', time: '09:25 AM', date: '2024-02-12' },
{ id: 3, fullName: 'Emily Johnson', designation: 'Student', department: 'Physics', status: 'Present', time: '08:40 AM', date: '2024-02-13' },
{ id: 3, fullName: 'Emily Johnson', designation: 'Student', department: 'Physics', status: 'Present', time: '08:35 AM', date: '2024-02-14' },
{ id: 3, fullName: 'Emily Johnson', designation: 'Student', department: 'Physics', status: 'Late', time: '09:25 AM', date: '2024-02-15' },
{ id: 3, fullName: 'Emily Johnson', designation: 'Student', department: 'Physics', status: 'Late', time: '09:25 AM', date: '2024-02-16' },
{ id: 3, fullName: 'Emily Johnson', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-17' },
{ id: 3, fullName: 'Emily Johnson', designation: 'Student', department: 'Physics', status: 'Late', time: '09:20 AM', date: '2024-02-18' },
{ id: 3, fullName: 'Emily Johnson', designation: 'Student', department: 'Physics', status: 'Late', time: '09:05 AM', date: '2024-02-19' },
{ id: 3, fullName: 'Emily Johnson', designation: 'Student', department: 'Physics', status: 'Present', time: '08:30 AM', date: '2024-02-20' },
{ id: 4, fullName: 'John', designation: 'Teacher', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-01' },
{ id: 4, fullName: 'John', designation: 'Teacher', department: 'Computer Science', status: 'Present', time: '08:35 AM', date: '2024-02-02' },
{ id: 4, fullName: 'John', designation: 'Teacher', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-03' },
{ id: 4, fullName: 'John', designation: 'Teacher', department: 'Computer Science', status: 'Present', time: '08:55 AM', date: '2024-02-04' },
{ id: 4, fullName: 'John', designation: 'Teacher', department: 'Computer Science', status: 'Late', time: '09:15 AM', date: '2024-02-05' },
{ id: 4, fullName: 'John', designation: 'Teacher', department: 'Computer Science', status: 'Present', time: '08:40 AM', date: '2024-02-06' },
{ id: 4, fullName: 'John', designation: 'Teacher', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-07' },
{ id: 4, fullName: 'John', designation: 'Teacher', department: 'Computer Science', status: 'Late', time: '09:05 AM', date: '2024-02-08' },
{ id: 4, fullName: 'John', designation: 'Teacher', department: 'Computer Science', status: 'Late', time: '09:15 AM', date: '2024-02-09' },
{ id: 4, fullName: 'John', designation: 'Teacher', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-10' },
{ id: 4, fullName: 'John', designation: 'Teacher', department: 'Computer Science', status: 'Present', time: '08:35 AM', date: '2024-02-11' },
{ id: 4, fullName: 'John', designation: 'Teacher', department: 'Computer Science', status: 'Late', time: '09:20 AM', date: '2024-02-12' },
{ id: 4, fullName: 'John', designation: 'Teacher', department: 'Computer Science', status: 'Present', time: '08:45 AM', date: '2024-02-13' },
{ id: 4, fullName: 'John', designation: 'Teacher', department: 'Computer Science', status: 'Present', time: '08:50 AM', date: '2024-02-14' },
{ id: 4, fullName: 'John', designation: 'Teacher', department: 'Computer Science', status: 'Present', time: '08:35 AM', date: '2024-02-15' },
{ id: 4, fullName: 'John', designation: 'Teacher', department: 'Computer Science', status: 'Present', time: '08:50 AM', date: '2024-02-16' },
{ id: 4, fullName: 'John', designation: 'Teacher', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-17' },
{ id: 4, fullName: 'John', designation: 'Teacher', department: 'Computer Science', status: 'Late', time: '09:25 AM', date: '2024-02-18' },
{ id: 4, fullName: 'John', designation: 'Teacher', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-19' },
{ id: 4, fullName: 'John', designation: 'Teacher', department: 'Computer Science', status: 'Late', time: '09:25 AM', date: '2024-02-20' },
{ id: 5, fullName: 'Alice Brown', designation: 'Student', department: 'Biology', status: 'Absent', time: 'N/A', date: '2024-02-01' },
{ id: 5, fullName: 'Alice Brown', designation: 'Student', department: 'Biology', status: 'Present', time: '08:30 AM', date: '2024-02-02' },
{ id: 5, fullName: 'Alice Brown', designation: 'Student', department: 'Biology', status: 'Absent', time: 'N/A', date: '2024-02-03' },
{ id: 5, fullName: 'Alice Brown', designation: 'Student', department: 'Biology', status: 'Present', time: '08:30 AM', date: '2024-02-04' },
{ id: 5, fullName: 'Alice Brown', designation: 'Student', department: 'Biology', status: 'Present', time: '08:40 AM', date: '2024-02-05' },
{ id: 5, fullName: 'Alice Brown', designation: 'Student', department: 'Biology', status: 'Late', time: '09:15 AM', date: '2024-02-06' },
{ id: 5, fullName: 'Alice Brown', designation: 'Student', department: 'Biology', status: 'Absent', time: 'N/A', date: '2024-02-07' },
{ id: 5, fullName: 'Alice Brown', designation: 'Student', department: 'Biology', status: 'Absent', time: 'N/A', date: '2024-02-08' },
{ id: 5, fullName: 'Alice Brown', designation: 'Student', department: 'Biology', status: 'Present', time: '08:50 AM', date: '2024-02-09' },
{ id: 5, fullName: 'Alice Brown', designation: 'Student', department: 'Biology', status: 'Present', time: '08:50 AM', date: '2024-02-10' },
{ id: 5, fullName: 'Alice Brown', designation: 'Student', department: 'Biology', status: 'Absent', time: 'N/A', date: '2024-02-11' },
{ id: 5, fullName: 'Alice Brown', designation: 'Student', department: 'Biology', status: 'Late', time: '09:10 AM', date: '2024-02-12' },
{ id: 5, fullName: 'Alice Brown', designation: 'Student', department: 'Biology', status: 'Absent', time: 'N/A', date: '2024-02-13' },
{ id: 5, fullName: 'Alice Brown', designation: 'Student', department: 'Biology', status: 'Late', time: '09:05 AM', date: '2024-02-14' },
{ id: 5, fullName: 'Alice Brown', designation: 'Student', department: 'Biology', status: 'Present', time: '08:30 AM', date: '2024-02-15' },
{ id: 5, fullName: 'Alice Brown', designation: 'Student', department: 'Biology', status: 'Late', time: '09:20 AM', date: '2024-02-16' },
{ id: 5, fullName: 'Alice Brown', designation: 'Student', department: 'Biology', status: 'Present', time: '08:45 AM', date: '2024-02-17' },
{ id: 5, fullName: 'Alice Brown', designation: 'Student', department: 'Biology', status: 'Present', time: '08:35 AM', date: '2024-02-18' },
{ id: 5, fullName: 'Alice Brown', designation: 'Student', department: 'Biology', status: 'Present', time: '08:40 AM', date: '2024-02-19' },
{ id: 5, fullName: 'Alice Brown', designation: 'Student', department: 'Biology', status: 'Late', time: '09:20 AM', date: '2024-02-20' },
{ id: 6, fullName: 'Michael Green', designation: 'Student', department: 'Chemistry', status: 'Absent', time: 'N/A', date: '2024-02-01' },
{ id: 6, fullName: 'Michael Green', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:20 AM', date: '2024-02-02' },
{ id: 6, fullName: 'Michael Green', designation: 'Student', department: 'Chemistry', status: 'Absent', time: 'N/A', date: '2024-02-03' },
{ id: 6, fullName: 'Michael Green', designation: 'Student', department: 'Chemistry', status: 'Absent', time: 'N/A', date: '2024-02-04' },
{ id: 6, fullName: 'Michael Green', designation: 'Student', department: 'Chemistry', status: 'Absent', time: 'N/A', date: '2024-02-05' },
{ id: 6, fullName: 'Michael Green', designation: 'Student', department: 'Chemistry', status: 'Absent', time: 'N/A', date: '2024-02-06' },
{ id: 6, fullName: 'Michael Green', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:25 AM', date: '2024-02-07' },
{ id: 6, fullName: 'Michael Green', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:05 AM', date: '2024-02-08' },
{ id: 6, fullName: 'Michael Green', designation: 'Student', department: 'Chemistry', status: 'Present', time: '08:50 AM', date: '2024-02-09' },
{ id: 6, fullName: 'Michael Green', designation: 'Student', department: 'Chemistry', status: 'Present', time: '08:30 AM', date: '2024-02-10' },
{ id: 6, fullName: 'Michael Green', designation: 'Student', department: 'Chemistry', status: 'Present', time: '08:40 AM', date: '2024-02-11' },
{ id: 6, fullName: 'Michael Green', designation: 'Student', department: 'Chemistry', status: 'Present', time: '08:45 AM', date: '2024-02-12' },
{ id: 6, fullName: 'Michael Green', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:25 AM', date: '2024-02-13' },
{ id: 6, fullName: 'Michael Green', designation: 'Student', department: 'Chemistry', status: 'Absent', time: 'N/A', date: '2024-02-14' },
{ id: 6, fullName: 'Michael Green', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:20 AM', date: '2024-02-15' },
{ id: 6, fullName: 'Michael Green', designation: 'Student', department: 'Chemistry', status: 'Present', time: '08:55 AM', date: '2024-02-16' },
{ id: 6, fullName: 'Michael Green', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:25 AM', date: '2024-02-17' },
{ id: 6, fullName: 'Michael Green', designation: 'Student', department: 'Chemistry', status: 'Absent', time: 'N/A', date: '2024-02-18' },
{ id: 6, fullName: 'Michael Green', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:20 AM', date: '2024-02-19' },
{ id: 6, fullName: 'Michael Green', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:15 AM', date: '2024-02-20' },
{ id: 7, fullName: 'Chris White', designation: 'Student', department: 'Physics', status: 'Present', time: '08:30 AM', date: '2024-02-01' },
{ id: 7, fullName: 'Chris White', designation: 'Student', department: 'Physics', status: 'Late', time: '09:05 AM', date: '2024-02-02' },
{ id: 7, fullName: 'Chris White', designation: 'Student', department: 'Physics', status: 'Present', time: '08:55 AM', date: '2024-02-03' },
{ id: 7, fullName: 'Chris White', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-04' },
{ id: 7, fullName: 'Chris White', designation: 'Student', department: 'Physics', status: 'Present', time: '08:40 AM', date: '2024-02-05' },
{ id: 7, fullName: 'Chris White', designation: 'Student', department: 'Physics', status: 'Late', time: '09:20 AM', date: '2024-02-06' },
{ id: 7, fullName: 'Chris White', designation: 'Student', department: 'Physics', status: 'Present', time: '08:50 AM', date: '2024-02-07' },
{ id: 7, fullName: 'Chris White', designation: 'Student', department: 'Physics', status: 'Present', time: '08:40 AM', date: '2024-02-08' },
{ id: 7, fullName: 'Chris White', designation: 'Student', department: 'Physics', status: 'Late', time: '09:10 AM', date: '2024-02-09' },
{ id: 7, fullName: 'Chris White', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-10' },
{ id: 7, fullName: 'Chris White', designation: 'Student', department: 'Physics', status: 'Present', time: '08:35 AM', date: '2024-02-11' },
{ id: 7, fullName: 'Chris White', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-12' },
{ id: 7, fullName: 'Chris White', designation: 'Student', department: 'Physics', status: 'Present', time: '08:35 AM', date: '2024-02-13' },
{ id: 7, fullName: 'Chris White', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-14' },
{ id: 7, fullName: 'Chris White', designation: 'Student', department: 'Physics', status: 'Present', time: '08:30 AM', date: '2024-02-15' },
{ id: 7, fullName: 'Chris White', designation: 'Student', department: 'Physics', status: 'Present', time: '08:45 AM', date: '2024-02-16' },
{ id: 7, fullName: 'Chris White', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-17' },
{ id: 7, fullName: 'Chris White', designation: 'Student', department: 'Physics', status: 'Late', time: '09:25 AM', date: '2024-02-18' },
{ id: 7, fullName: 'Chris White', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-19' },
{ id: 7, fullName: 'Chris White', designation: 'Student', department: 'Physics', status: 'Present', time: '08:30 AM', date: '2024-02-20' },
{ id: 8, fullName: 'Jessica Lee', designation: 'Student', department: 'Mathematics', status: 'Present', time: '08:50 AM', date: '2024-02-01' },
{ id: 8, fullName: 'Jessica Lee', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:05 AM', date: '2024-02-02' },
{ id: 8, fullName: 'Jessica Lee', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:25 AM', date: '2024-02-03' },
{ id: 8, fullName: 'Jessica Lee', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:15 AM', date: '2024-02-04' },
{ id: 8, fullName: 'Jessica Lee', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:25 AM', date: '2024-02-05' },
{ id: 8, fullName: 'Jessica Lee', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:25 AM', date: '2024-02-06' },
{ id: 8, fullName: 'Jessica Lee', designation: 'Student', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-07' },
{ id: 8, fullName: 'Jessica Lee', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:20 AM', date: '2024-02-08' },
{ id: 8, fullName: 'Jessica Lee', designation: 'Student', department: 'Mathematics', status: 'Present', time: '08:40 AM', date: '2024-02-09' },
{ id: 8, fullName: 'Jessica Lee', designation: 'Student', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-10' },
{ id: 8, fullName: 'Jessica Lee', designation: 'Student', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-11' },
{ id: 8, fullName: 'Jessica Lee', designation: 'Student', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-12' },
{ id: 8, fullName: 'Jessica Lee', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:20 AM', date: '2024-02-13' },
{ id: 8, fullName: 'Jessica Lee', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:15 AM', date: '2024-02-14' },
{ id: 8, fullName: 'Jessica Lee', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:10 AM', date: '2024-02-15' },
{ id: 8, fullName: 'Jessica Lee', designation: 'Student', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-16' },
{ id: 8, fullName: 'Jessica Lee', designation: 'Student', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-17' },
{ id: 8, fullName: 'Jessica Lee', designation: 'Student', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-18' },
{ id: 8, fullName: 'Jessica Lee', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:10 AM', date: '2024-02-19' },
{ id: 8, fullName: 'Jessica Lee', designation: 'Student', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-20' },
{ id: 9, fullName: 'David Kim', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:55 AM', date: '2024-02-01' },
{ id: 9, fullName: 'David Kim', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:45 AM', date: '2024-02-02' },
{ id: 9, fullName: 'David Kim', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:40 AM', date: '2024-02-03' },
{ id: 9, fullName: 'David Kim', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:20 AM', date: '2024-02-04' },
{ id: 9, fullName: 'David Kim', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:25 AM', date: '2024-02-05' },
{ id: 9, fullName: 'David Kim', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:40 AM', date: '2024-02-06' },
{ id: 9, fullName: 'David Kim', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:30 AM', date: '2024-02-07' },
{ id: 9, fullName: 'David Kim', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-08' },
{ id: 9, fullName: 'David Kim', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-09' },
{ id: 9, fullName: 'David Kim', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-10' },
{ id: 9, fullName: 'David Kim', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:30 AM', date: '2024-02-11' },
{ id: 9, fullName: 'David Kim', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:35 AM', date: '2024-02-12' },
{ id: 9, fullName: 'David Kim', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-13' },
{ id: 9, fullName: 'David Kim', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-14' },
{ id: 9, fullName: 'David Kim', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-15' },
{ id: 9, fullName: 'David Kim', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:15 AM', date: '2024-02-16' },
{ id: 9, fullName: 'David Kim', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:05 AM', date: '2024-02-17' },
{ id: 9, fullName: 'David Kim', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-18' },
{ id: 9, fullName: 'David Kim', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:45 AM', date: '2024-02-19' },
{ id: 9, fullName: 'David Kim', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-20' },
{ id: 10, fullName: 'Sophia Clark', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-01' },
{ id: 10, fullName: 'Sophia Clark', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:15 AM', date: '2024-02-02' },
{ id: 10, fullName: 'Sophia Clark', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:10 AM', date: '2024-02-03' },
{ id: 10, fullName: 'Sophia Clark', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-04' },
{ id: 10, fullName: 'Sophia Clark', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:25 AM', date: '2024-02-05' },
{ id: 10, fullName: 'Sophia Clark', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:30 AM', date: '2024-02-06' },
{ id: 10, fullName: 'Sophia Clark', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-07' },
{ id: 10, fullName: 'Sophia Clark', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:10 AM', date: '2024-02-08' },
{ id: 10, fullName: 'Sophia Clark', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-09' },
{ id: 10, fullName: 'Sophia Clark', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-10' },
{ id: 10, fullName: 'Sophia Clark', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-11' },
{ id: 10, fullName: 'Sophia Clark', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:35 AM', date: '2024-02-12' },
{ id: 10, fullName: 'Sophia Clark', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-13' },
{ id: 10, fullName: 'Sophia Clark', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-14' },
{ id: 10, fullName: 'Sophia Clark', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:30 AM', date: '2024-02-15' },
{ id: 10, fullName: 'Sophia Clark', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:50 AM', date: '2024-02-16' },
{ id: 10, fullName: 'Sophia Clark', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:45 AM', date: '2024-02-17' },
{ id: 10, fullName: 'Sophia Clark', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:55 AM', date: '2024-02-18' },
{ id: 10, fullName: 'Sophia Clark', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:50 AM', date: '2024-02-19' },
{ id: 10, fullName: 'Sophia Clark', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:55 AM', date: '2024-02-20' },
{ id: 11, fullName: 'Daniel Martinez', designation: 'Student', department: 'Physics', status: 'Late', time: '09:10 AM', date: '2024-02-01' },
{ id: 11, fullName: 'Daniel Martinez', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-02' },
{ id: 11, fullName: 'Daniel Martinez', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-03' },
{ id: 11, fullName: 'Daniel Martinez', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-04' },
{ id: 11, fullName: 'Daniel Martinez', designation: 'Student', department: 'Physics', status: 'Late', time: '09:25 AM', date: '2024-02-05' },
{ id: 11, fullName: 'Daniel Martinez', designation: 'Student', department: 'Physics', status: 'Present', time: '08:45 AM', date: '2024-02-06' },
{ id: 11, fullName: 'Daniel Martinez', designation: 'Student', department: 'Physics', status: 'Present', time: '08:35 AM', date: '2024-02-07' },
{ id: 11, fullName: 'Daniel Martinez', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-08' },
{ id: 11, fullName: 'Daniel Martinez', designation: 'Student', department: 'Physics', status: 'Late', time: '09:10 AM', date: '2024-02-09' },
{ id: 11, fullName: 'Daniel Martinez', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-10' },
{ id: 11, fullName: 'Daniel Martinez', designation: 'Student', department: 'Physics', status: 'Present', time: '08:30 AM', date: '2024-02-11' },
{ id: 11, fullName: 'Daniel Martinez', designation: 'Student', department: 'Physics', status: 'Present', time: '08:55 AM', date: '2024-02-12' },
{ id: 11, fullName: 'Daniel Martinez', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-13' },
{ id: 11, fullName: 'Daniel Martinez', designation: 'Student', department: 'Physics', status: 'Late', time: '09:05 AM', date: '2024-02-14' },
{ id: 11, fullName: 'Daniel Martinez', designation: 'Student', department: 'Physics', status: 'Late', time: '09:10 AM', date: '2024-02-15' },
{ id: 11, fullName: 'Daniel Martinez', designation: 'Student', department: 'Physics', status: 'Late', time: '09:05 AM', date: '2024-02-16' },
{ id: 11, fullName: 'Daniel Martinez', designation: 'Student', department: 'Physics', status: 'Late', time: '09:05 AM', date: '2024-02-17' },
{ id: 11, fullName: 'Daniel Martinez', designation: 'Student', department: 'Physics', status: 'Present', time: '08:45 AM', date: '2024-02-18' },
{ id: 11, fullName: 'Daniel Martinez', designation: 'Student', department: 'Physics', status: 'Present', time: '08:55 AM', date: '2024-02-19' },
{ id: 11, fullName: 'Daniel Martinez', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-20' },
{ id: 12, fullName: 'Olivia Hernandez', designation: 'Student', department: 'Biology', status: 'Present', time: '08:50 AM', date: '2024-02-01' },
{ id: 12, fullName: 'Olivia Hernandez', designation: 'Student', department: 'Biology', status: 'Absent', time: 'N/A', date: '2024-02-02' },
{ id: 12, fullName: 'Olivia Hernandez', designation: 'Student', department: 'Biology', status: 'Absent', time: 'N/A', date: '2024-02-03' },
{ id: 12, fullName: 'Olivia Hernandez', designation: 'Student', department: 'Biology', status: 'Absent', time: 'N/A', date: '2024-02-04' },
{ id: 12, fullName: 'Olivia Hernandez', designation: 'Student', department: 'Biology', status: 'Present', time: '08:35 AM', date: '2024-02-05' },
{ id: 12, fullName: 'Olivia Hernandez', designation: 'Student', department: 'Biology', status: 'Late', time: '09:05 AM', date: '2024-02-06' },
{ id: 12, fullName: 'Olivia Hernandez', designation: 'Student', department: 'Biology', status: 'Present', time: '08:45 AM', date: '2024-02-07' },
{ id: 12, fullName: 'Olivia Hernandez', designation: 'Student', department: 'Biology', status: 'Absent', time: 'N/A', date: '2024-02-08' },
{ id: 12, fullName: 'Olivia Hernandez', designation: 'Student', department: 'Biology', status: 'Absent', time: 'N/A', date: '2024-02-09' },
{ id: 12, fullName: 'Olivia Hernandez', designation: 'Student', department: 'Biology', status: 'Absent', time: 'N/A', date: '2024-02-10' },
{ id: 12, fullName: 'Olivia Hernandez', designation: 'Student', department: 'Biology', status: 'Late', time: '09:05 AM', date: '2024-02-11' },
{ id: 12, fullName: 'Olivia Hernandez', designation: 'Student', department: 'Biology', status: 'Late', time: '09:05 AM', date: '2024-02-12' },
{ id: 12, fullName: 'Olivia Hernandez', designation: 'Student', department: 'Biology', status: 'Late', time: '09:05 AM', date: '2024-02-13' },
{ id: 12, fullName: 'Olivia Hernandez', designation: 'Student', department: 'Biology', status: 'Absent', time: 'N/A', date: '2024-02-14' },
{ id: 12, fullName: 'Olivia Hernandez', designation: 'Student', department: 'Biology', status: 'Present', time: '08:40 AM', date: '2024-02-15' },
{ id: 12, fullName: 'Olivia Hernandez', designation: 'Student', department: 'Biology', status: 'Late', time: '09:05 AM', date: '2024-02-16' },
{ id: 12, fullName: 'Olivia Hernandez', designation: 'Student', department: 'Biology', status: 'Absent', time: 'N/A', date: '2024-02-17' },
{ id: 12, fullName: 'Olivia Hernandez', designation: 'Student', department: 'Biology', status: 'Present', time: '08:50 AM', date: '2024-02-18' },
{ id: 12, fullName: 'Olivia Hernandez', designation: 'Student', department: 'Biology', status: 'Absent', time: 'N/A', date: '2024-02-19' },
{ id: 12, fullName: 'Olivia Hernandez', designation: 'Student', department: 'Biology', status: 'Late', time: '09:05 AM', date: '2024-02-20' },
{ id: 13, fullName: 'William Scott', designation: 'Teacher', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-01' },
{ id: 13, fullName: 'William Scott', designation: 'Teacher', department: 'Mathematics', status: 'Present', time: '08:40 AM', date: '2024-02-02' },
{ id: 13, fullName: 'William Scott', designation: 'Teacher', department: 'Mathematics', status: 'Present', time: '08:30 AM', date: '2024-02-03' },
{ id: 13, fullName: 'William Scott', designation: 'Teacher', department: 'Mathematics', status: 'Late', time: '09:20 AM', date: '2024-02-04' },
{ id: 13, fullName: 'William Scott', designation: 'Teacher', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-05' },
{ id: 13, fullName: 'William Scott', designation: 'Teacher', department: 'Mathematics', status: 'Late', time: '09:20 AM', date: '2024-02-06' },
{ id: 13, fullName: 'William Scott', designation: 'Teacher', department: 'Mathematics', status: 'Late', time: '09:15 AM', date: '2024-02-07' },
{ id: 13, fullName: 'William Scott', designation: 'Teacher', department: 'Mathematics', status: 'Late', time: '09:20 AM', date: '2024-02-08' },
{ id: 13, fullName: 'William Scott', designation: 'Teacher', department: 'Mathematics', status: 'Late', time: '09:10 AM', date: '2024-02-09' },
{ id: 13, fullName: 'William Scott', designation: 'Teacher', department: 'Mathematics', status: 'Present', time: '08:35 AM', date: '2024-02-10' },
{ id: 13, fullName: 'William Scott', designation: 'Teacher', department: 'Mathematics', status: 'Late', time: '09:20 AM', date: '2024-02-11' },
{ id: 13, fullName: 'William Scott', designation: 'Teacher', department: 'Mathematics', status: 'Present', time: '08:50 AM', date: '2024-02-12' },
{ id: 13, fullName: 'William Scott', designation: 'Teacher', department: 'Mathematics', status: 'Late', time: '09:25 AM', date: '2024-02-13' },
{ id: 13, fullName: 'William Scott', designation: 'Teacher', department: 'Mathematics', status: 'Late', time: '09:15 AM', date: '2024-02-14' },
{ id: 13, fullName: 'William Scott', designation: 'Teacher', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-15' },
{ id: 13, fullName: 'William Scott', designation: 'Teacher', department: 'Mathematics', status: 'Present', time: '08:45 AM', date: '2024-02-16' },
{ id: 13, fullName: 'William Scott', designation: 'Teacher', department: 'Mathematics', status: 'Present', time: '08:35 AM', date: '2024-02-17' },
{ id: 13, fullName: 'William Scott', designation: 'Teacher', department: 'Mathematics', status: 'Late', time: '09:05 AM', date: '2024-02-18' },
{ id: 13, fullName: 'William Scott', designation: 'Teacher', department: 'Mathematics', status: 'Present', time: '08:35 AM', date: '2024-02-19' },
{ id: 13, fullName: 'William Scott', designation: 'Teacher', department: 'Mathematics', status: 'Present', time: '08:40 AM', date: '2024-02-20' },
{ id: 14, fullName: 'Isabella Adams', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-01' },
{ id: 14, fullName: 'Isabella Adams', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:55 AM', date: '2024-02-02' },
{ id: 14, fullName: 'Isabella Adams', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-03' },
{ id: 14, fullName: 'Isabella Adams', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:50 AM', date: '2024-02-04' },
{ id: 14, fullName: 'Isabella Adams', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:55 AM', date: '2024-02-05' },
{ id: 14, fullName: 'Isabella Adams', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:25 AM', date: '2024-02-06' },
{ id: 14, fullName: 'Isabella Adams', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-07' },
{ id: 14, fullName: 'Isabella Adams', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:55 AM', date: '2024-02-08' },
{ id: 14, fullName: 'Isabella Adams', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-09' },
{ id: 14, fullName: 'Isabella Adams', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-10' },
{ id: 14, fullName: 'Isabella Adams', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-11' },
{ id: 14, fullName: 'Isabella Adams', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:10 AM', date: '2024-02-12' },
{ id: 14, fullName: 'Isabella Adams', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:20 AM', date: '2024-02-13' },
{ id: 14, fullName: 'Isabella Adams', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:40 AM', date: '2024-02-14' },
{ id: 14, fullName: 'Isabella Adams', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:15 AM', date: '2024-02-15' },
{ id: 14, fullName: 'Isabella Adams', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:15 AM', date: '2024-02-16' },
{ id: 14, fullName: 'Isabella Adams', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:55 AM', date: '2024-02-17' },
{ id: 14, fullName: 'Isabella Adams', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:30 AM', date: '2024-02-18' },
{ id: 14, fullName: 'Isabella Adams', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:55 AM', date: '2024-02-19' },
{ id: 14, fullName: 'Isabella Adams', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:35 AM', date: '2024-02-20' },
{ id: 15, fullName: 'James Carter', designation: 'Student', department: 'Chemistry', status: 'Absent', time: 'N/A', date: '2024-02-01' },
{ id: 15, fullName: 'James Carter', designation: 'Student', department: 'Chemistry', status: 'Absent', time: 'N/A', date: '2024-02-02' },
{ id: 15, fullName: 'James Carter', designation: 'Student', department: 'Chemistry', status: 'Absent', time: 'N/A', date: '2024-02-03' },
{ id: 15, fullName: 'James Carter', designation: 'Student', department: 'Chemistry', status: 'Present', time: '08:40 AM', date: '2024-02-04' },
{ id: 15, fullName: 'James Carter', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:05 AM', date: '2024-02-05' },
{ id: 15, fullName: 'James Carter', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:20 AM', date: '2024-02-06' },
{ id: 15, fullName: 'James Carter', designation: 'Student', department: 'Chemistry', status: 'Absent', time: 'N/A', date: '2024-02-07' },
{ id: 15, fullName: 'James Carter', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:10 AM', date: '2024-02-08' },
{ id: 15, fullName: 'James Carter', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:15 AM', date: '2024-02-09' },
{ id: 15, fullName: 'James Carter', designation: 'Student', department: 'Chemistry', status: 'Present', time: '08:50 AM', date: '2024-02-10' },
{ id: 15, fullName: 'James Carter', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:20 AM', date: '2024-02-11' },
{ id: 15, fullName: 'James Carter', designation: 'Student', department: 'Chemistry', status: 'Absent', time: 'N/A', date: '2024-02-12' },
{ id: 15, fullName: 'James Carter', designation: 'Student', department: 'Chemistry', status: 'Absent', time: 'N/A', date: '2024-02-13' },
{ id: 15, fullName: 'James Carter', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:05 AM', date: '2024-02-14' },
{ id: 15, fullName: 'James Carter', designation: 'Student', department: 'Chemistry', status: 'Present', time: '08:45 AM', date: '2024-02-15' },
{ id: 15, fullName: 'James Carter', designation: 'Student', department: 'Chemistry', status: 'Present', time: '08:35 AM', date: '2024-02-16' },
{ id: 15, fullName: 'James Carter', designation: 'Student', department: 'Chemistry', status: 'Present', time: '08:30 AM', date: '2024-02-17' },
{ id: 15, fullName: 'James Carter', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:10 AM', date: '2024-02-18' },
{ id: 15, fullName: 'James Carter', designation: 'Student', department: 'Chemistry', status: 'Absent', time: 'N/A', date: '2024-02-19' },
{ id: 15, fullName: 'James Carter', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:15 AM', date: '2024-02-20' },
{ id: 16, fullName: 'Charlotte Lewis', designation: 'Student', department: 'Biology', status: 'Late', time: '09:20 AM', date: '2024-02-01' },
{ id: 16, fullName: 'Charlotte Lewis', designation: 'Student', department: 'Biology', status: 'Late', time: '09:20 AM', date: '2024-02-02' },
{ id: 16, fullName: 'Charlotte Lewis', designation: 'Student', department: 'Biology', status: 'Present', time: '08:50 AM', date: '2024-02-03' },
{ id: 16, fullName: 'Charlotte Lewis', designation: 'Student', department: 'Biology', status: 'Absent', time: 'N/A', date: '2024-02-04' },
{ id: 16, fullName: 'Charlotte Lewis', designation: 'Student', department: 'Biology', status: 'Present', time: '08:55 AM', date: '2024-02-05' },
{ id: 16, fullName: 'Charlotte Lewis', designation: 'Student', department: 'Biology', status: 'Absent', time: 'N/A', date: '2024-02-06' },
{ id: 16, fullName: 'Charlotte Lewis', designation: 'Student', department: 'Biology', status: 'Present', time: '08:50 AM', date: '2024-02-07' },
{ id: 16, fullName: 'Charlotte Lewis', designation: 'Student', department: 'Biology', status: 'Late', time: '09:25 AM', date: '2024-02-08' },
{ id: 16, fullName: 'Charlotte Lewis', designation: 'Student', department: 'Biology', status: 'Absent', time: 'N/A', date: '2024-02-09' },
{ id: 16, fullName: 'Charlotte Lewis', designation: 'Student', department: 'Biology', status: 'Present', time: '08:30 AM', date: '2024-02-10' },
{ id: 16, fullName: 'Charlotte Lewis', designation: 'Student', department: 'Biology', status: 'Absent', time: 'N/A', date: '2024-02-11' },
{ id: 16, fullName: 'Charlotte Lewis', designation: 'Student', department: 'Biology', status: 'Late', time: '09:25 AM', date: '2024-02-12' },
{ id: 16, fullName: 'Charlotte Lewis', designation: 'Student', department: 'Biology', status: 'Present', time: '08:55 AM', date: '2024-02-13' },
{ id: 16, fullName: 'Charlotte Lewis', designation: 'Student', department: 'Biology', status: 'Present', time: '08:40 AM', date: '2024-02-14' },
{ id: 16, fullName: 'Charlotte Lewis', designation: 'Student', department: 'Biology', status: 'Late', time: '09:05 AM', date: '2024-02-15' },
{ id: 16, fullName: 'Charlotte Lewis', designation: 'Student', department: 'Biology', status: 'Late', time: '09:05 AM', date: '2024-02-16' },
{ id: 16, fullName: 'Charlotte Lewis', designation: 'Student', department: 'Biology', status: 'Present', time: '08:50 AM', date: '2024-02-17' },
{ id: 16, fullName: 'Charlotte Lewis', designation: 'Student', department: 'Biology', status: 'Absent', time: 'N/A', date: '2024-02-18' },
{ id: 16, fullName: 'Charlotte Lewis', designation: 'Student', department: 'Biology', status: 'Absent', time: 'N/A', date: '2024-02-19' },
{ id: 16, fullName: 'Charlotte Lewis', designation: 'Student', department: 'Biology', status: 'Present', time: '08:50 AM', date: '2024-02-20' },
{ id: 17, fullName: 'Benjamin Walker', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:05 AM', date: '2024-02-01' },
{ id: 17, fullName: 'Benjamin Walker', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:45 AM', date: '2024-02-02' },
{ id: 17, fullName: 'Benjamin Walker', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-03' },
{ id: 17, fullName: 'Benjamin Walker', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-04' },
{ id: 17, fullName: 'Benjamin Walker', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:30 AM', date: '2024-02-05' },
{ id: 17, fullName: 'Benjamin Walker', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:20 AM', date: '2024-02-06' },
{ id: 17, fullName: 'Benjamin Walker', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:45 AM', date: '2024-02-07' },
{ id: 17, fullName: 'Benjamin Walker', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-08' },
{ id: 17, fullName: 'Benjamin Walker', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-09' },
{ id: 17, fullName: 'Benjamin Walker', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-10' },
{ id: 17, fullName: 'Benjamin Walker', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-11' },
{ id: 17, fullName: 'Benjamin Walker', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:15 AM', date: '2024-02-12' },
{ id: 17, fullName: 'Benjamin Walker', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:40 AM', date: '2024-02-13' },
{ id: 17, fullName: 'Benjamin Walker', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:20 AM', date: '2024-02-14' },
{ id: 17, fullName: 'Benjamin Walker', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:50 AM', date: '2024-02-15' },
{ id: 17, fullName: 'Benjamin Walker', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:50 AM', date: '2024-02-16' },
{ id: 17, fullName: 'Benjamin Walker', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-17' },
{ id: 17, fullName: 'Benjamin Walker', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:45 AM', date: '2024-02-18' },
{ id: 17, fullName: 'Benjamin Walker', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:35 AM', date: '2024-02-19' },
{ id: 17, fullName: 'Benjamin Walker', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:10 AM', date: '2024-02-20' },
{ id: 18, fullName: 'Mia Hall', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-01' },
{ id: 18, fullName: 'Mia Hall', designation: 'Student', department: 'Physics', status: 'Present', time: '08:30 AM', date: '2024-02-02' },
{ id: 18, fullName: 'Mia Hall', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-03' },
{ id: 18, fullName: 'Mia Hall', designation: 'Student', department: 'Physics', status: 'Late', time: '09:20 AM', date: '2024-02-04' },
{ id: 18, fullName: 'Mia Hall', designation: 'Student', department: 'Physics', status: 'Present', time: '08:40 AM', date: '2024-02-05' },
{ id: 18, fullName: 'Mia Hall', designation: 'Student', department: 'Physics', status: 'Late', time: '09:15 AM', date: '2024-02-06' },
{ id: 18, fullName: 'Mia Hall', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-07' },
{ id: 18, fullName: 'Mia Hall', designation: 'Student', department: 'Physics', status: 'Present', time: '08:40 AM', date: '2024-02-08' },
{ id: 18, fullName: 'Mia Hall', designation: 'Student', department: 'Physics', status: 'Present', time: '08:55 AM', date: '2024-02-09' },
{ id: 18, fullName: 'Mia Hall', designation: 'Student', department: 'Physics', status: 'Present', time: '08:40 AM', date: '2024-02-10' },
{ id: 18, fullName: 'Mia Hall', designation: 'Student', department: 'Physics', status: 'Late', time: '09:10 AM', date: '2024-02-11' },
{ id: 18, fullName: 'Mia Hall', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-12' },
{ id: 18, fullName: 'Mia Hall', designation: 'Student', department: 'Physics', status: 'Present', time: '08:45 AM', date: '2024-02-13' },
{ id: 18, fullName: 'Mia Hall', designation: 'Student', department: 'Physics', status: 'Present', time: '08:50 AM', date: '2024-02-14' },
{ id: 18, fullName: 'Mia Hall', designation: 'Student', department: 'Physics', status: 'Late', time: '09:15 AM', date: '2024-02-15' },
{ id: 18, fullName: 'Mia Hall', designation: 'Student', department: 'Physics', status: 'Present', time: '08:45 AM', date: '2024-02-16' },
{ id: 18, fullName: 'Mia Hall', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-17' },
{ id: 18, fullName: 'Mia Hall', designation: 'Student', department: 'Physics', status: 'Present', time: '08:50 AM', date: '2024-02-18' },
{ id: 18, fullName: 'Mia Hall', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-19' },
{ id: 18, fullName: 'Mia Hall', designation: 'Student', department: 'Physics', status: 'Present', time: '08:30 AM', date: '2024-02-20' },
{ id: 19, fullName: 'Ethan Allen', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:20 AM', date: '2024-02-01' },
{ id: 19, fullName: 'Ethan Allen', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-02' },
{ id: 19, fullName: 'Ethan Allen', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:55 AM', date: '2024-02-03' },
{ id: 19, fullName: 'Ethan Allen', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-04' },
{ id: 19, fullName: 'Ethan Allen', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:10 AM', date: '2024-02-05' },
{ id: 19, fullName: 'Ethan Allen', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-06' },
{ id: 19, fullName: 'Ethan Allen', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:25 AM', date: '2024-02-07' },
{ id: 19, fullName: 'Ethan Allen', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:45 AM', date: '2024-02-08' },
{ id: 19, fullName: 'Ethan Allen', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:55 AM', date: '2024-02-09' },
{ id: 19, fullName: 'Ethan Allen', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:10 AM', date: '2024-02-10' },
{ id: 19, fullName: 'Ethan Allen', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:50 AM', date: '2024-02-11' },
{ id: 19, fullName: 'Ethan Allen', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-12' },
{ id: 19, fullName: 'Ethan Allen', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-13' },
{ id: 19, fullName: 'Ethan Allen', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:15 AM', date: '2024-02-14' },
{ id: 19, fullName: 'Ethan Allen', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:35 AM', date: '2024-02-15' },
{ id: 19, fullName: 'Ethan Allen', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:30 AM', date: '2024-02-16' },
{ id: 19, fullName: 'Ethan Allen', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:50 AM', date: '2024-02-17' },
{ id: 19, fullName: 'Ethan Allen', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:35 AM', date: '2024-02-18' },
{ id: 19, fullName: 'Ethan Allen', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-19' },
{ id: 19, fullName: 'Ethan Allen', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:05 AM', date: '2024-02-20' },
{ id: 20, fullName: 'Harper Young', designation: 'Student', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-01' },
{ id: 20, fullName: 'Harper Young', designation: 'Student', department: 'Mathematics', status: 'Present', time: '08:50 AM', date: '2024-02-02' },
{ id: 20, fullName: 'Harper Young', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:25 AM', date: '2024-02-03' },
{ id: 20, fullName: 'Harper Young', designation: 'Student', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-04' },
{ id: 20, fullName: 'Harper Young', designation: 'Student', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-05' },
{ id: 20, fullName: 'Harper Young', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:10 AM', date: '2024-02-06' },
{ id: 20, fullName: 'Harper Young', designation: 'Student', department: 'Mathematics', status: 'Present', time: '08:35 AM', date: '2024-02-07' },
{ id: 20, fullName: 'Harper Young', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:10 AM', date: '2024-02-08' },
{ id: 20, fullName: 'Harper Young', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:20 AM', date: '2024-02-09' },
{ id: 20, fullName: 'Harper Young', designation: 'Student', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-10' },
{ id: 20, fullName: 'Harper Young', designation: 'Student', department: 'Mathematics', status: 'Present', time: '08:40 AM', date: '2024-02-11' },
{ id: 20, fullName: 'Harper Young', designation: 'Student', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-12' },
{ id: 20, fullName: 'Harper Young', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:20 AM', date: '2024-02-13' },
{ id: 20, fullName: 'Harper Young', designation: 'Student', department: 'Mathematics', status: 'Present', time: '08:55 AM', date: '2024-02-14' },
{ id: 20, fullName: 'Harper Young', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:10 AM', date: '2024-02-15' },
{ id: 20, fullName: 'Harper Young', designation: 'Student', department: 'Mathematics', status: 'Present', time: '08:50 AM', date: '2024-02-16' },
{ id: 20, fullName: 'Harper Young', designation: 'Student', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-17' },
{ id: 20, fullName: 'Harper Young', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:10 AM', date: '2024-02-18' },
{ id: 20, fullName: 'Harper Young', designation: 'Student', department: 'Mathematics', status: 'Late', time: '09:05 AM', date: '2024-02-19' },
{ id: 20, fullName: 'Harper Young', designation: 'Student', department: 'Mathematics', status: 'Absent', time: 'N/A', date: '2024-02-20' },
{ id: 21, fullName: 'Alexander King', designation: 'Student', department: 'Physics', status: 'Present', time: '08:30 AM', date: '2024-02-01' },
{ id: 21, fullName: 'Alexander King', designation: 'Student', department: 'Physics', status: 'Late', time: '09:10 AM', date: '2024-02-02' },
{ id: 21, fullName: 'Alexander King', designation: 'Student', department: 'Physics', status: 'Late', time: '09:10 AM', date: '2024-02-03' },
{ id: 21, fullName: 'Alexander King', designation: 'Student', department: 'Physics', status: 'Present', time: '08:55 AM', date: '2024-02-04' },
{ id: 21, fullName: 'Alexander King', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-05' },
{ id: 21, fullName: 'Alexander King', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-06' },
{ id: 21, fullName: 'Alexander King', designation: 'Student', department: 'Physics', status: 'Present', time: '08:30 AM', date: '2024-02-07' },
{ id: 21, fullName: 'Alexander King', designation: 'Student', department: 'Physics', status: 'Late', time: '09:10 AM', date: '2024-02-08' },
{ id: 21, fullName: 'Alexander King', designation: 'Student', department: 'Physics', status: 'Present', time: '08:30 AM', date: '2024-02-09' },
{ id: 21, fullName: 'Alexander King', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-10' },
{ id: 21, fullName: 'Alexander King', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-11' },
{ id: 21, fullName: 'Alexander King', designation: 'Student', department: 'Physics', status: 'Present', time: '08:50 AM', date: '2024-02-12' },
{ id: 21, fullName: 'Alexander King', designation: 'Student', department: 'Physics', status: 'Late', time: '09:15 AM', date: '2024-02-13' },
{ id: 21, fullName: 'Alexander King', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-14' },
{ id: 21, fullName: 'Alexander King', designation: 'Student', department: 'Physics', status: 'Late', time: '09:25 AM', date: '2024-02-15' },
{ id: 21, fullName: 'Alexander King', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-16' },
{ id: 21, fullName: 'Alexander King', designation: 'Student', department: 'Physics', status: 'Late', time: '09:15 AM', date: '2024-02-17' },
{ id: 21, fullName: 'Alexander King', designation: 'Student', department: 'Physics', status: 'Late', time: '09:15 AM', date: '2024-02-18' },
{ id: 21, fullName: 'Alexander King', designation: 'Student', department: 'Physics', status: 'Late', time: '09:25 AM', date: '2024-02-19' },
{ id: 21, fullName: 'Alexander King', designation: 'Student', department: 'Physics', status: 'Absent', time: 'N/A', date: '2024-02-20' },
{ id: 22, fullName: 'Amelia Nelson', designation: 'Student', department: 'Chemistry', status: 'Present', time: '08:35 AM', date: '2024-02-01' },
{ id: 22, fullName: 'Amelia Nelson', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:05 AM', date: '2024-02-02' },
{ id: 22, fullName: 'Amelia Nelson', designation: 'Student', department: 'Chemistry', status: 'Present', time: '08:35 AM', date: '2024-02-03' },
{ id: 22, fullName: 'Amelia Nelson', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:15 AM', date: '2024-02-04' },
{ id: 22, fullName: 'Amelia Nelson', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:15 AM', date: '2024-02-05' },
{ id: 22, fullName: 'Amelia Nelson', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:15 AM', date: '2024-02-06' },
{ id: 22, fullName: 'Amelia Nelson', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:25 AM', date: '2024-02-07' },
{ id: 22, fullName: 'Amelia Nelson', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:05 AM', date: '2024-02-08' },
{ id: 22, fullName: 'Amelia Nelson', designation: 'Student', department: 'Chemistry', status: 'Absent', time: 'N/A', date: '2024-02-09' },
{ id: 22, fullName: 'Amelia Nelson', designation: 'Student', department: 'Chemistry', status: 'Present', time: '08:50 AM', date: '2024-02-10' },
{ id: 22, fullName: 'Amelia Nelson', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:10 AM', date: '2024-02-11' },
{ id: 22, fullName: 'Amelia Nelson', designation: 'Student', department: 'Chemistry', status: 'Absent', time: 'N/A', date: '2024-02-12' },
{ id: 22, fullName: 'Amelia Nelson', designation: 'Student', department: 'Chemistry', status: 'Absent', time: 'N/A', date: '2024-02-13' },
{ id: 22, fullName: 'Amelia Nelson', designation: 'Student', department: 'Chemistry', status: 'Present', time: '08:50 AM', date: '2024-02-14' },
{ id: 22, fullName: 'Amelia Nelson', designation: 'Student', department: 'Chemistry', status: 'Absent', time: 'N/A', date: '2024-02-15' },
{ id: 22, fullName: 'Amelia Nelson', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:10 AM', date: '2024-02-16' },
{ id: 22, fullName: 'Amelia Nelson', designation: 'Student', department: 'Chemistry', status: 'Late', time: '09:20 AM', date: '2024-02-17' },
{ id: 22, fullName: 'Amelia Nelson', designation: 'Student', department: 'Chemistry', status: 'Absent', time: 'N/A', date: '2024-02-18' },
{ id: 22, fullName: 'Amelia Nelson', designation: 'Student', department: 'Chemistry', status: 'Absent', time: 'N/A', date: '2024-02-19' },
{ id: 22, fullName: 'Amelia Nelson', designation: 'Student', department: 'Chemistry', status: 'Absent', time: 'N/A', date: '2024-02-20' },
{ id: 23, fullName: 'Lucas Robinson', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-01' },
{ id: 23, fullName: 'Lucas Robinson', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:35 AM', date: '2024-02-02' },
{ id: 23, fullName: 'Lucas Robinson', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-03' },
{ id: 23, fullName: 'Lucas Robinson', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-04' },
{ id: 23, fullName: 'Lucas Robinson', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-05' },
{ id: 23, fullName: 'Lucas Robinson', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:25 AM', date: '2024-02-06' },
{ id: 23, fullName: 'Lucas Robinson', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:20 AM', date: '2024-02-07' },
{ id: 23, fullName: 'Lucas Robinson', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:25 AM', date: '2024-02-08' },
{ id: 23, fullName: 'Lucas Robinson', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-09' },
{ id: 23, fullName: 'Lucas Robinson', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:10 AM', date: '2024-02-10' },
{ id: 23, fullName: 'Lucas Robinson', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-11' },
{ id: 23, fullName: 'Lucas Robinson', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-12' },
{ id: 23, fullName: 'Lucas Robinson', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:55 AM', date: '2024-02-13' },
{ id: 23, fullName: 'Lucas Robinson', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:55 AM', date: '2024-02-14' },
{ id: 23, fullName: 'Lucas Robinson', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:05 AM', date: '2024-02-15' },
{ id: 23, fullName: 'Lucas Robinson', designation: 'Student', department: 'Engineering', status: 'Absent', time: 'N/A', date: '2024-02-16' },
{ id: 23, fullName: 'Lucas Robinson', designation: 'Student', department: 'Engineering', status: 'Present', time: '08:30 AM', date: '2024-02-17' },
{ id: 23, fullName: 'Lucas Robinson', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:20 AM', date: '2024-02-18' },
{ id: 23, fullName: 'Lucas Robinson', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:15 AM', date: '2024-02-19' },
{ id: 23, fullName: 'Lucas Robinson', designation: 'Student', department: 'Engineering', status: 'Late', time: '09:10 AM', date: '2024-02-20' },
{ id: 24, fullName: 'Ella Baker', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:20 AM', date: '2024-02-01' },
{ id: 24, fullName: 'Ella Baker', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:55 AM', date: '2024-02-02' },
{ id: 24, fullName: 'Ella Baker', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-03' },
{ id: 24, fullName: 'Ella Baker', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-04' },
{ id: 24, fullName: 'Ella Baker', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-05' },
{ id: 24, fullName: 'Ella Baker', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-06' },
{ id: 24, fullName: 'Ella Baker', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:15 AM', date: '2024-02-07' },
{ id: 24, fullName: 'Ella Baker', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-08' },
{ id: 24, fullName: 'Ella Baker', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:25 AM', date: '2024-02-09' },
{ id: 24, fullName: 'Ella Baker', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-10' },
{ id: 24, fullName: 'Ella Baker', designation: 'Student', department: 'Computer Science', status: 'Absent', time: 'N/A', date: '2024-02-11' },
{ id: 24, fullName: 'Ella Baker', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:15 AM', date: '2024-02-12' },
{ id: 24, fullName: 'Ella Baker', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:30 AM', date: '2024-02-13' },
{ id: 24, fullName: 'Ella Baker', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:05 AM', date: '2024-02-14' },
{ id: 24, fullName: 'Ella Baker', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:30 AM', date: '2024-02-15' },
{ id: 24, fullName: 'Ella Baker', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:50 AM', date: '2024-02-16' },
{ id: 24, fullName: 'Ella Baker', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:25 AM', date: '2024-02-17' },
{ id: 24, fullName: 'Ella Baker', designation: 'Student', department: 'Computer Science', status: 'Late', time: '09:20 AM', date: '2024-02-18' },
{ id: 24, fullName: 'Ella Baker', designation: 'Student', department: 'Computer Science', status: 'Present', time: '08:45 AM', date: '2024-02-19' },
{ id: 24, fullName: 'Ella Baker', designation: 'Student', department: 'Computer Science', status: 'Late', time: '//09:20 AM', date: '2024-02-20' },
      ];
      
      getLoggedinStudents() {
        return this.loggedinStudents;
      }
}